#!/bin/bash
# Regenerate every derived form of the TAWC app icon from its one source,
# `app/icon.svg` (an Inkscape document — edit it there).
#
# Generated outputs, all checked in:
#
#   app/src/main/res/drawable/ic_tawc_logo.xml          the mark at full size
#   app/src/main/res/drawable/ic_launcher_foreground.xml  + safe-zone scale
#   app/src/main/res/values/icon_colors.xml             background colour
#   fastlane/metadata/android/en-US/images/icon.png     F-Droid store icon
#
# Run this after every edit to app/icon.svg and commit the results
# together. Nothing runs it automatically: the app build must not depend on
# an SVG rasteriser, and these files change about once a year.
#
# `--check` re-derives everything and reports any output that has drifted,
# without writing. Use it to confirm the checked-in files still match the
# source.
#
# What the source may contain: paths, groups, and Inkscape's own metadata.
# The translation to Android's vector format is structural (`pathData` is
# SVG path syntax), so anything that is not a path has to be converted to
# one first — in Inkscape, select all and use Path > Object to Path, which
# covers shapes, strokes, and text. The script fails loudly naming what it
# could not translate rather than quietly dropping it from the icon.
#
# The background colour comes from the SVG's page colour (Inkscape:
# Document Properties > Background), which is why it is a real colour in
# the document rather than a drawn rectangle.
#
# Requires: python3, and one of rsvg-convert / inkscape / magick for the
# PNG.
#
# Usage:
#   scripts/gen-icon.sh                # regenerate everything
#   scripts/gen-icon.sh --check        # verify, write nothing
#   scripts/gen-icon.sh --size=1024    # store icon at another size
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

SOURCE="$ROOT_DIR/app/icon.svg"
RES_DIR="$ROOT_DIR/app/src/main/res"
PNG_OUT="$ROOT_DIR/fastlane/metadata/android/en-US/images/icon.png"
SIZE=512
CHECK=0

# Fraction of the canvas the mark occupies inside the adaptive icon. The
# launcher masks the outer edge away, so the foreground has to sit inside
# the safe zone (72dp of 108dp = 0.667); 0.60 leaves a little margin. The
# store icon uses the same scale so it matches what launchers draw.
SAFE_ZONE_SCALE=0.60

for arg in "$@"; do
    case "$arg" in
        --size=*) SIZE="${arg#--size=}" ;;
        --check) CHECK=1 ;;
        -h|--help) sed -n '2,36p' "$0" | sed 's/^# \?//'; exit 0 ;;
        *) echo "unknown argument: $arg" >&2; exit 1 ;;
    esac
done

command -v python3 >/dev/null || { echo "ERROR: python3 not found" >&2; exit 1; }
[ -f "$SOURCE" ] || { echo "ERROR: missing $SOURCE" >&2; exit 1; }

work="$(mktemp -d -t tawc-icon-XXXXXX)"
trap 'rm -rf "$work"' EXIT

python3 - "$SOURCE" "$work" "$SAFE_ZONE_SCALE" <<'PY'
import re, sys, xml.etree.ElementTree as ET

source, outdir, safe_scale = sys.argv[1], sys.argv[2], float(sys.argv[3])
SVG = "{http://www.w3.org/2000/svg}"
INK = "{http://www.inkscape.org/namespaces/inkscape}"
SODI = "{http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd}"

GENERATED = ("Generated by scripts/gen-icon.sh from app/icon.svg — do not\n"
             "     edit. Change the icon in app/icon.svg and re-run the script.")


def die(msg, hint=None):
    out = "ERROR: %s\n  in %s" % (msg, source)
    if hint:
        out += "\n  %s" % hint
    sys.exit(out)


def style_of(el):
    """Presentation attributes and the style="" property list, merged."""
    props = {}
    for key in ("fill", "fill-opacity", "stroke", "stroke-opacity", "display",
                "opacity"):
        if el.get(key) is not None:
            props[key] = el.get(key)
    for decl in (el.get("style") or "").split(";"):
        if ":" in decl:
            k, v = decl.split(":", 1)
            props[k.strip()] = v.strip()
    return props


def parse_transform(spec):
    """SVG transform list -> Android <group> attribute dicts, outermost first.

    Android applies one scale, one rotation and one translation per group in
    a fixed order, so each SVG function becomes its own nested group. That
    keeps composed transforms exact instead of trying to merge them.
    """
    groups = []
    for name, argstr in re.findall(r"(\w+)\s*\(([^)]*)\)", spec or ""):
        args = [float(a) for a in re.split(r"[\s,]+", argstr.strip()) if a]
        if name == "translate":
            tx, ty = (args + [0.0])[:2]
            groups.append({"translateX": tx, "translateY": ty})
        elif name == "scale":
            sx = args[0]
            sy = args[1] if len(args) > 1 else sx
            groups.append({"scaleX": sx, "scaleY": sy})
        elif name == "rotate":
            g = {"rotation": args[0]}
            if len(args) == 3:
                g["pivotX"], g["pivotY"] = args[1], args[2]
            groups.append(g)
        elif name == "matrix":
            a, b, c, d, e, f = args
            if b or c:
                die("transform matrix(%s) mixes rotation and skew" % argstr,
                    "flatten it in Inkscape (Path > Object to Path)")
            groups.append({"translateX": e, "translateY": f,
                           "scaleX": a, "scaleY": d})
        else:
            die("unsupported transform %s()" % name)
    return groups


paths = []          # (depth-ordered) list of (group-stack, path attrs)


def walk(parent, stack):
    for el in parent:
        tag = el.tag
        if tag in (SVG + "defs", SVG + "metadata", SODI + "namedview",
                   "{http://www.w3.org/2000/svg}title",
                   "{http://www.w3.org/2000/svg}desc"):
            continue
        props = style_of(el)
        if props.get("display") == "none":
            continue
        if tag == SVG + "g":
            walk(el, stack + parse_transform(el.get("transform")))
        elif tag == SVG + "path":
            if el.get("transform"):
                die("<path> carries a transform",
                    "flatten it in Inkscape (Path > Object to Path)")
            stroke = props.get("stroke", "none")
            if stroke not in ("none", ""):
                die("<path> has a painted stroke (%s)" % stroke,
                    "convert strokes to fills in Inkscape "
                    "(Path > Stroke to Path)")
            fill = props.get("fill", "#000000")
            if fill.startswith("url("):
                die("<path> is filled with a gradient or pattern",
                    "the Android vector format cannot express it here")
            paths.append((stack, {
                "d": el.get("d"),
                "fill": fill.upper() if fill.startswith("#") else fill,
                "alpha": props.get("fill-opacity"),
            }))
        elif tag == SVG + "text":
            # Inkscape leaves empty text frames behind when text is
            # converted to paths; those are harmless. Real text is not.
            if "".join(el.itertext()).strip():
                die("<text> element still holds text",
                    "convert it in Inkscape (Path > Object to Path)")
        elif tag in (SVG + "rect", SVG + "circle", SVG + "ellipse",
                     SVG + "line", SVG + "polyline", SVG + "polygon"):
            die("<%s> is a shape, not a path" % tag[len(SVG):],
                "convert it in Inkscape (Path > Object to Path)")
        else:
            die("unhandled element <%s>" % tag.replace(SVG, ""))


root = ET.parse(source).getroot()
if root.tag != SVG + "svg":
    die("root element is not <svg>")
view = root.get("viewBox")
if not view:
    die("<svg> has no viewBox")
vx, vy, vw, vh = [float(n) for n in re.split(r"[\s,]+", view.strip())]
if (vx, vy) != (0.0, 0.0):
    die("viewBox origin is not 0,0")

namedview = root.find(SODI + "namedview")
bg = namedview.get("pagecolor") if namedview is not None else None
if not bg or not re.fullmatch(r"#[0-9a-fA-F]{6}", bg):
    die("no usable sodipodi:namedview/@pagecolor",
        "set it in Inkscape: Document Properties > Background")
bg = bg.upper()

walk(root, [])
if not paths:
    die("no paths found")


def num(v):
    return ("%g" % v)


def android_vector(scale=None, note=""):
    """Emit an Android vector drawable, optionally inside a scale group."""
    out = ['<?xml version="1.0" encoding="utf-8"?>',
           "<!-- %s%s -->" % (note, GENERATED),
           '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
           '    android:width="%sdp"' % num(vw),
           '    android:height="%sdp"' % num(vh),
           '    android:viewportWidth="%s"' % num(vw),
           '    android:viewportHeight="%s">' % num(vh)]
    indent = "    "
    if scale is not None:
        out += ["", "%s<group" % indent,
                '%s    android:pivotX="%s"' % (indent, num(vw / 2)),
                '%s    android:pivotY="%s"' % (indent, num(vh / 2)),
                '%s    android:scaleX="%s"' % (indent, num(scale)),
                '%s    android:scaleY="%s">' % (indent, num(scale))]
        indent += "    "
    for stack, p in paths:
        depth = indent
        for g in stack:
            attrs = " ".join('android:%s="%s"' % (k, num(v))
                             for k, v in sorted(g.items()))
            out.append("%s<group %s>" % (depth, attrs))
            depth += "    "
        out.append("%s<path" % depth)
        out.append('%s    android:fillColor="%s"' % (depth, p["fill"]))
        if p["alpha"] not in (None, "1", "1.0"):
            out.append('%s    android:fillAlpha="%s"' % (depth, p["alpha"]))
        out.append('%s    android:pathData="%s" />' % (depth, p["d"]))
        for _ in stack:
            depth = depth[:-4]
            out.append("%s</group>" % depth)
    if scale is not None:
        out.append("    </group>")
    out.append("</vector>")
    return "\n".join(out) + "\n"


def store_svg():
    """Background + safe-zone-scaled mark, for the raster store icon."""
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<svg xmlns="http://www.w3.org/2000/svg" width="%s" height="%s" '
           'viewBox="0 0 %s %s">' % (num(vw), num(vh), num(vw), num(vh)),
           '  <rect width="%s" height="%s" fill="%s"/>' % (num(vw), num(vh), bg),
           '  <g transform="translate(%s,%s) scale(%s) translate(%s,%s)">'
           % (num(vw / 2), num(vh / 2), num(safe_scale),
              num(-vw / 2), num(-vh / 2))]
    for stack, p in paths:
        pre = "".join(
            '<g transform="translate(%s,%s) rotate(%s) scale(%s,%s)">'
            % (num(g.get("translateX", 0)), num(g.get("translateY", 0)),
               num(g.get("rotation", 0)), num(g.get("scaleX", 1)),
               num(g.get("scaleY", 1))) for g in stack)
        alpha = ('' if p["alpha"] in (None, "1", "1.0")
                 else ' fill-opacity="%s"' % p["alpha"])
        out.append('    %s<path fill="%s"%s d="%s"/>%s'
                   % (pre, p["fill"], alpha, p["d"], "</g>" * len(stack)))
    out += ["  </g>", "</svg>"]
    return "\n".join(out) + "\n"


colors = ('<?xml version="1.0" encoding="utf-8"?>\n'
          "<!-- %s -->\n"
          "<resources>\n"
          '    <color name="tawc_icon_bg">%s</color>\n'
          "</resources>\n" % (GENERATED, bg))

logo_note = ("The TAWC mark at full size (ic_launcher_foreground without\n"
             "     the adaptive-icon safe-zone scale). Launcher-row "
             "fallback icon\n     for graphical entries with no usable "
             "icon.\n\n     ")
fg_note = ("The adaptive launcher icon's foreground layer.\n\n     ")

for name, text in (
    ("ic_tawc_logo.xml", android_vector(note=logo_note)),
    ("ic_launcher_foreground.xml", android_vector(safe_scale, note=fg_note)),
    ("icon_colors.xml", colors),
    ("store.svg", store_svg()),
):
    with open("%s/%s" % (outdir, name), "w") as fh:
        fh.write(text)

print("%d paths, background %s" % (len(paths), bg))
PY

# ---------------------------------------------------------------------------
# Raster the store icon. Any of these renderers produces the same image for
# this artwork (flat fills, no text, no filters); take whichever is present.
render_png() {
    local dest="$1"
    mkdir -p "$(dirname "$dest")"
    if command -v rsvg-convert >/dev/null; then
        rsvg-convert -w "$SIZE" -h "$SIZE" -o "$dest" "$work/store.svg"
    elif command -v inkscape >/dev/null; then
        inkscape "$work/store.svg" -w "$SIZE" -h "$SIZE" -o "$dest" \
            >/dev/null 2>&1
    elif command -v magick >/dev/null; then
        magick -background none "$work/store.svg" \
            -resize "${SIZE}x${SIZE}" "$dest"
    else
        return 2
    fi
}

vector_outputs=(
    "$RES_DIR/drawable/ic_tawc_logo.xml:ic_tawc_logo.xml"
    "$RES_DIR/drawable/ic_launcher_foreground.xml:ic_launcher_foreground.xml"
    "$RES_DIR/values/icon_colors.xml:icon_colors.xml"
)

if [ "$CHECK" = 1 ]; then
    drift=0
    for pair in "${vector_outputs[@]}"; do
        dest="${pair%%:*}"; src="$work/${pair##*:}"
        if ! diff -q "$dest" "$src" >/dev/null 2>&1; then
            echo "DRIFT: $dest"
            diff -u "$dest" "$src" | sed -n '3,15p' || true
            drift=1
        fi
    done
    # The PNG is deliberately not byte-compared: different rasteriser
    # versions produce different bytes for identical artwork. Check the
    # properties that matter and leave the pixels to a re-run.
    if [ ! -f "$PNG_OUT" ]; then
        echo "DRIFT: $PNG_OUT missing"
        drift=1
    elif command -v identify >/dev/null; then
        dims="$(identify -format '%wx%h' "$PNG_OUT")"
        if [ "$dims" != "${SIZE}x${SIZE}" ]; then
            echo "DRIFT: $PNG_OUT is $dims, expected ${SIZE}x${SIZE}"
            drift=1
        fi
    fi
    [ "$drift" = 0 ] && echo "==> icon outputs match app/icon.svg"
    exit "$drift"
fi

for pair in "${vector_outputs[@]}"; do
    dest="${pair%%:*}"; src="$work/${pair##*:}"
    cp "$src" "$dest"
    echo "==> wrote $dest"
done

if render_png "$PNG_OUT"; then
    echo "==> wrote $PNG_OUT (${SIZE}x${SIZE})"
else
    echo "ERROR: need one of rsvg-convert, inkscape, or magick for the PNG" >&2
    exit 1
fi
