// Session-id word lists of relays before the RFC 1751 switch (sshyeet
// client 46kr0c202g, `internal/sid/words.go`), used with the author's
// permission. Only for accepting the id such a relay assigns (see
// `sid::legacy`); indices are positional, so both lists are frozen.

pub(crate) const ADJECTIVES: [&str; 256] = [
    "able", "aged", "agile", "airy", "alert", "alive", "amber", "ample",
    "apt", "arid", "avid", "awake", "aware", "azure", "balmy", "basic",
    "bold", "brave", "brief", "brisk", "broad", "bumpy", "busy", "calm",
    "canny", "chief", "civic", "civil", "clean", "clear", "close", "cool",
    "coral", "cozy", "crisp", "curly", "cute", "dandy", "dark", "dear",
    "deep", "deft", "dense", "dizzy", "dry", "dusky", "dusty", "eager",
    "early", "easy", "elder", "elfin", "elite", "empty", "equal", "even",
    "exact", "extra", "faint", "fair", "fancy", "fast", "fine", "first",
    "fit", "fizzy", "fleet", "foggy", "fond", "frank", "free", "fresh",
    "funky", "funny", "fuzzy", "giant", "giddy", "glad", "good", "grand",
    "great", "green", "grown", "gutsy", "hairy", "handy", "happy", "hardy",
    "hasty", "hazy", "hefty", "hilly", "husky", "icy", "ideal", "idle",
    "inky", "inner", "ionic", "iron", "jade", "jazzy", "jolly", "juicy",
    "jumpy", "just", "keen", "kind", "known", "lanky", "large", "last",
    "late", "lazy", "leafy", "lean", "level", "light", "lithe", "local",
    "lofty", "lone", "long", "loud", "loyal", "lucid", "lucky", "lunar",
    "lush", "magic", "major", "manic", "merry", "mild", "minty", "misty",
    "moral", "mossy", "muddy", "mute", "neat", "nervy", "new", "nice",
    "nifty", "noble", "noisy", "north", "novel", "oaken", "odd", "olive",
    "open", "outer", "oval", "pale", "peppy", "perky", "plain", "plump",
    "plush", "polar", "posh", "prime", "proud", "pure", "quick", "quiet",
    "rapid", "rare", "ready", "regal", "rich", "rigid", "ripe", "rosy",
    "rough", "round", "royal", "ruddy", "sandy", "sassy", "savvy", "sharp",
    "shiny", "showy", "shy", "silky", "sleek", "slick", "slim", "small",
    "smart", "smoky", "snowy", "snug", "social", "soft", "solar", "solid",
    "sonic", "spare", "spicy", "spry", "square", "stable", "stark", "steady",
    "steep", "still", "stormy", "stout", "sturdy", "suave", "subtle", "sunny",
    "super", "sweet", "swift", "tall", "tame", "tan", "tart", "tender",
    "tidy", "tiny", "top", "tough", "trim", "true", "trusty", "twin",
    "upbeat", "upper", "urban", "vague", "valid", "vast", "velvet", "vivid",
    "vocal", "wacky", "warm", "wary", "wavy", "whole", "wide", "wild",
    "windy", "wise", "witty", "woolly", "young", "zany", "zesty", "zippy",
];

pub(crate) const NOUNS: [&str; 256] = [
    "alpaca", "ant", "ape", "auk", "baboon", "badger", "bat", "bear",
    "beaver", "bee", "beetle", "bison", "boar", "bobcat", "bongo", "bream",
    "buck", "bug", "bull", "bunny", "camel", "canary", "carp", "cat",
    "chick", "cicada", "civet", "clam", "cobra", "cod", "collie", "colt",
    "condor", "corgi", "cougar", "cow", "coyote", "crab", "crane", "crow",
    "cub", "cuckoo", "deer", "dingo", "dodo", "doe", "dog", "donkey",
    "dove", "dragon", "drake", "duck", "eagle", "earwig", "eel", "egret",
    "elk", "emu", "ermine", "ewe", "falcon", "fawn", "ferret", "finch",
    "fish", "flea", "foal", "fox", "frog", "gannet", "gator", "gecko",
    "gerbil", "gibbon", "gnat", "gnu", "goat", "goose", "gopher", "grebe",
    "grouse", "gull", "guppy", "hare", "hawk", "hen", "heron", "hippo",
    "hog", "hornet", "horse", "hound", "hyena", "hyrax", "ibex", "ibis",
    "iguana", "impala", "jackal", "jaguar", "jay", "kestrel", "kite", "kitten",
    "kiwi", "koala", "koi", "krill", "ladybug", "lamb", "lapwing", "lark",
    "lemur", "leopard", "limpet", "linnet", "lion", "lizard", "llama", "lobster",
    "locust", "loon", "lynx", "macaw", "magpie", "mallard", "mamba", "manatee",
    "manta", "marlin", "marmot", "marten", "mayfly", "meerkat", "mink", "minnow",
    "mole", "monkey", "moose", "moth", "mouse", "mule", "mullet", "mussel",
    "narwhal", "newt", "numbat", "ocelot", "octopus", "okapi", "orca", "oriole",
    "osprey", "otter", "owl", "ox", "oyster", "panda", "panther", "parrot",
    "peacock", "pelican", "penguin", "perch", "petrel", "pig", "pigeon", "piglet",
    "pika", "pike", "plover", "polecat", "pony", "poodle", "possum", "prawn",
    "puffin", "pug", "puma", "puppy", "python", "quail", "quokka", "rabbit",
    "racoon", "ram", "rat", "raven", "ray", "rhino", "robin", "rook",
    "rooster", "sable", "salmon", "sardine", "sawfish", "scallop", "seal", "serval",
    "shark", "sheep", "shrew", "shrimp", "skink", "skunk", "sloth", "slug",
    "smelt", "snail", "snake", "snipe", "sole", "sparrow", "spider", "sponge",
    "squid", "stag", "stoat", "stork", "sunfish", "swallow", "swan", "tadpole",
    "tapir", "termite", "tern", "terrier", "tetra", "thrush", "tiger", "toad",
    "toucan", "trout", "tuna", "turkey", "turtle", "urchin", "viper", "vole",
    "vulture", "wallaby", "walrus", "warthog", "wasp", "weasel", "weevil", "whale",
    "whippet", "wildcat", "wolf", "wombat", "worm", "wren", "yak", "zebra",
];
